spring:
  application:
    name: boot-server
  # JPA, H2(??? ?? DB), MySQL
  profiles:
    active: dev
    # Docker? ??? ?? ???? ??? ?? prod? ???...

# ?? ? -> ?? ??
server:
#  port: 8080
  port: ${SERVER_PORT:8080}